plugins{
    id 'java-gradle-plugin'
    id 'groovy'
    id 'java'
    id 'ivy-publish'
    id 'com.gradle.plugin-publish' version '1.3.0'
    id 'nrlssc.gradle' version '4.0.126'
}


compileJava.options.encoding = 'UTF-8'

hgit{
    forceGit = true
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    api gradleApi()
    implementation localGroovy()
    api 'mil.navy.nrlssc:gplugin-commons:3.0.21'
    api 'mil.navy.nrlssc:add-copyright:2.0.25'
    implementation 'io.github.classgraph:classgraph:4.8.78'
    implementation 'org.xhtmlrenderer:flying-saucer-pdf:9.1.22'
    implementation 'eu.de-swaef.pdf:Markdown2Pdf:2.0.1'
    

    testImplementation gradleTestKit(),
            'junit:junit:4.12'
}
gradlePlugin {
    website = 'https://github.com/nrl-gradle/util-plugin'
    vcsUrl = 'https://github.com/nrl-gradle/util-plugin.git'
    //noinspection GroovyAssignabilityCheck
    plugins {
        create('utilPlugin') {
            id = 'nrlssc.util'
            tags = ['utilities', 'build', 'diagram']
            displayName = 'Utility Tasks Plugin'
            description = 'Adds several extra utility tasks specifically geared towards internal development'
            implementationClass = 'nrlssc.gradle.UtilPlugin'
        }
    }
}
